static XDS_CLASSES: [&str; 8] = [
    "Current",
    "Future",
    "Channel",
    "Miscellaneous",
    "Public service",
    "Reserved",
    "Private data",
    "End",
];

static XDS_PROGRAM_TYPES: [&str; 96] = [
    "Education",
    "Entertainment",
    "Movie",
    "News",
    "Religious",
    "Sports",
    "Other",
    "Action",
    "Advertisement",
    "Animated",
    "Anthology",
    "Automobile",
    "Awards",
    "Baseball",
    "Basketball",
    "Bulletin",
    "Business",
    "Classical",
    "College",
    "Combat",
    "Comedy",
    "Commentary",
    "Concert",
    "Consumer",
    "Contemporary",
    "Crime",
    "Dance",
    "Documentary",
    "Drama",
    "Elementary",
    "Erotica",
    "Exercise",
    "Fantasy",
    "Farm",
    "Fashion",
    "Fiction",
    "Food",
    "Football",
    "Foreign",
    "Fund-Raiser",
    "Game/Quiz",
    "Garden",
    "Golf",
    "Government",
    "Health",
    "High_School",
    "History",
    "Hobby",
    "Hockey",
    "Home",
    "Horror",
    "Information",
    "Instruction",
    "International",
    "Interview",
    "Language",
    "Legal",
    "Live",
    "Local",
    "Math",
    "Medical",
    "Meeting",
    "Military",
    "Mini-Series",
    "Music",
    "Mystery",
    "National",
    "Nature",
    "Police",
    "Politics",
    "Premiere",
    "Pre-Recorded",
    "Product",
    "Professional",
    "Public",
    "Racing",
    "Reading",
    "Repair",
    "Repeat",
    "Review",
    "Romance",
    "Science",
    "Series",
    "Service",
    "Shopping",
    "Soap_Opera",
    "Special",
    "Suspense",
    "Talk",
    "Technical",
    "Tennis",
    "Travel",
    "Variety",
    "Video",
    "Weather",
    "Western",
];

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum XdsClass {
    Current = 0,
    Future = 1,
    Channel = 2,
    Misc = 3,
    Public = 4,
    Reserved = 5,
    Private = 6,
    End = 7,
    OutOfBand = 0x40,
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum XdsCurrentFutureType {
    PinStartTime = 1,
    LengthAndCurrentTime = 2,
    ProgramName = 3,
    ProgramType = 4,
    ContentAdvisory = 5,
    AudioServices = 6,
    Cgms = 8,
    AspectRatioInfo = 9,
    ProgramDesc1 = 0x10,
    ProgramDesc2 = 0x11,
    ProgramDesc3 = 0x12,
    ProgramDesc4 = 0x13,
    ProgramDesc5 = 0x14,
    ProgramDesc6 = 0x15,
    ProgramDesc7 = 0x16,
    ProgramDesc8 = 0x17,
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum XdsChannelType {
    NetworkName = 1,
    CallLettersAndChannel = 2,
    Tsid = 4,
}

#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum XdsMiscType {
    TimeOfDay = 1,
    LocalTimeZone = 4,
    OutOfBandChannelNumber = 0x40,
}
#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]

pub enum XdsType {
    Misc(XdsMiscType),
    Channel(XdsChannelType),
}
