/// CCExtractor C bindings generated by bindgen
///
/// using structs cc_subtitle, eia608_screen
#[allow(clippy::all)]
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::sync::atomic::{AtomicI64, Ordering};

static TS_START_OF_XDS: AtomicI64 = AtomicI64::new(-1); // Time at which we switched to XDS mode, =-1 hasn't happened yet
                                                        // Usage example:
                                                        // TS_START_OF_XDS.store(new_value, Ordering::SeqCst);
                                                        // let value = TS_START_OF_XDS.load(Ordering::SeqCst);

use crate::{
    bindings::{cc_subtitle, eia608_screen},
    xds::common_constants::*,
};

use crate::xds::common_types::*;
